### ISSUE TITLE
highlight option

### ISSUE THREAD

**Issue by MMesch** [nonbili/purescript-markdown-it#1]
Hey, thanks for this library! Did you ever try running the `highlight` option with a purescript function (e.g. with highligh.js or even just a simple purescript function)? I get a

```
renderer.js:58 Uncaught TypeError: highlighted.indexOf is not a function
    at Object.default_rules.fence (renderer.js:58)
    at Renderer.render (renderer.js:332)
    at MarkdownIt.render (index.js:544)
    at exports.render_ (ps.js:10521)
    at ps.js:7895
    at Object.exports.unsafePerformEffect (ps.js:6081)
    at ps.js:10591
    at ps.js:10597
    at ps.js:10618
    at ps.js:11771
```

Not sure whether I am doing anything wrong here or whether there is an issue passing the purescript function object to markdownit. Any idea how to solve this?

**Comment by rnons** [comment]
Good catch, thanks.
